<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{de4c17ca-6601-4dc2-9e9d-aef8e0f082a2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Counter : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Counter := Counter + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>